# Generated by Django 4.2 on 2023-05-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adress_book',
            new_name='AddressBook',
        ),
    ]
